trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - '*.md'

pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - '*.md'

pool:
  vmImage: 'windows-latest'

parameters:
  - name: deploy
    displayName: Deploy
    type: boolean
    default: false

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: Build_Test
    displayName: Build and Test
    jobs:
      - job: Build_Test
        displayName: Build and Test
        steps:
          - bash: dotnet tool install Cake.Tool --version 1.3.0 --global
          - bash: dotnet cake
      - job: NuGet_Package
        displayName: NuGet Package
        condition:
          in(
            succeeded('Build and Test'),
            and(succeeded(), eq('${{ parameters.deploy }}', 'true')),
            and(succeeded(), startsWith(variables['Build.SourceBranchName'], 'v'))
          )
        steps:
          - bash: ./cicd/package.sh $(Build.SourceBranchName)
          - publish: $(System.DefaultWorkingDirectory)/src/PgPartner/bin/Release
            artifact: NuGetPackage


  - stage: Deploy
    dependsOn: Build_Test
    condition:
      in(
        succeeded('Build and Test'),
        and(succeeded(), eq('${{ parameters.deploy }}', 'true')),
        and(succeeded(), startsWith(variables['Build.SourceBranchName'], 'v'))
      )
    jobs:
      - job: Deploy
        steps:
          - download: current
            artifact: NuGetPackage
          - bash: ./cicd/deploy.sh $(NUGET_KEY)
    
