trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - '*.md'

pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - '*.md'

pool:
  vmImage: 'windows-latest'

parameters:
  - name: deploy
    displayName: Deploy
    type: boolean
    default: false

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: Build_Test
    displayName: Build and Test
    jobs:
      - job: Build_Test
        displayName: Build and Test
        steps:
          - bash: dotnet tool install Cake.Tool --version 1.3.0 --global
            displayName: Install Cake Tool
          - bash: dotnet cake
            displayName: Build and Test
          - bash: ./cicd/package.sh $(Build.SourceBranchName)
            condition:
              in(
                succeeded(),
                and(succeeded(), eq('${{ parameters.deploy }}', 'true')),
                and(succeeded(), startsWith(variables['Build.SourceBranchName'], 'v'))
              )
            displayName: Build Package
          - publish: $(System.DefaultWorkingDirectory)/src/PgPartner/bin/Release
            displayName: Publish Release Artifacts
            artifact: NuGetPackage
            condition:
              in(
                succeeded(),
                and(succeeded(), eq('${{ parameters.deploy }}', 'true')),
                and(succeeded(), startsWith(variables['Build.SourceBranchName'], 'v'))
              )

  - stage: Deploy
    dependsOn: Build_Test
    condition:
      in(
        succeeded(),
        and(succeeded(), eq('${{ parameters.deploy }}', 'true')),
        and(succeeded(), startsWith(variables['Build.SourceBranchName'], 'v'))
      )
    jobs:
      - job: Deploy
        steps:
          - task: DownloadPipelineArtifact@2
            displayName: Download Release Artifacts
            inputs:
              artifact: NuGetPackage
              path: $(System.DefaultWorkingDirectory)/Release
          - bash: ./cicd/deploy.sh $(NUGET_KEY)
            displayName: Deploy
    
